// Page copy. `name` lines become the hollow neon headline and `line` the
// hollow neon English description (display font). Everything set in small
// type — the Chinese name, zone, body and facts — is in Chinese.
// `accent` / `accentMono` colour the rail dot and index in each palette.
//
// Sources: NASA planetary fact sheets and mission pages (MESSENGER, Juno,
// Cassini, Voyager 2, New Horizons); IAU 2006 resolution B5/B6 (Pluto);
// Irwin et al. 2024, MNRAS 527 (true colours of Uranus and Neptune).

export const PAGES = [
  {
    key: 'hero',
    title: 'Solar System',
    rail: '太阳系',
    eyebrow: '粒子太阳系 · 一颗恒星与九个世界',
    name: ['SOLAR', 'SYSTEM'],
    line: 'One star, nine worlds, drawn in light.',
    body: '向下滚动，从太阳出发，依次飞越九大行星。移动光标会像引力透镜一样把粒子弯成光环，点击会放出一圈太阳风冲击波，按住拖动可以让行星自转（首页拖动可以加快公转）。右上角可切换单色 / 多色，并调节荧光强度、字体与音量。',
    accent: '#ffc24a',
    accentMono: '#ffa23a',
  },
  {
    key: 'sun',
    title: 'The Sun',
    rail: '太阳',
    cn: '太阳 · 恒星',
    zone: 'G2V 型主序星 · 太阳系中心',
    accent: '#ffb347',
    accentMono: '#ff7a1a',
    name: ['THE SUN'],
    line: 'A star that holds 99.86% of all the mass in the solar system.',
    body: '太阳约有 46 亿岁，核心温度约 1500 万 °C，每秒把约 400 万吨物质转化为能量。阳光离开太阳表面后，约 8 分 20 秒抵达地球。边缘粉红色的拱形是日珥，向外流散的是日冕和太阳风。',
    facts: [['直径', '139.2 万 km'], ['表面温度', '约 5500 °C'], ['年龄', '约 46 亿年']],
  },
  {
    key: 'mercury',
    title: 'Mercury',
    rail: '水星',
    cn: '水星 · 类地行星',
    zone: '距日 0.39 AU · 第 1 颗行星',
    accent: '#c9c2b6',
    accentMono: '#9fbdda',
    name: ['MERCURY'],
    line: 'The swiftest planet, scorched by day and frozen by night.',
    body: '水星离太阳最近，体积也最小，绕太阳一圈只要 88 天。它几乎没有大气保温，白天地表可达 430 °C，夜间降到 −180 °C。由于自转很慢，水星上从日出到下一次日出要经过 176 个地球日。',
    facts: [['直径', '4,879 km'], ['公转周期', '88 天'], ['一昼夜', '176 地球日']],
  },
  {
    key: 'venus',
    title: 'Venus',
    rail: '金星',
    cn: '金星 · 类地行星',
    zone: '距日 0.72 AU · 第 2 颗行星',
    accent: '#e9cd8d',
    accentMono: '#9fbdda',
    name: ['VENUS'],
    line: 'A runaway greenhouse wrapped in clouds of sulfuric acid.',
    body: '金星与地球大小相近，却被浓厚的二氧化碳大气包裹，地表气压约为地球的 92 倍，温度约 465 °C，比水星还热。它逆向自转，转一圈要 243 个地球日，比公转一圈（225 天）还长；高空云层却只需约 4 天就能绕行一周。',
    facts: [['直径', '12,104 km'], ['地表温度', '约 465 °C'], ['自转', '243 天 · 逆向']],
  },
  {
    key: 'earth',
    title: 'Earth and the Moon',
    rail: '地球',
    cn: '地球与月球 · 类地行星',
    zone: '距日 1 AU · 第 3 颗行星',
    accent: '#4fa6e8',
    accentMono: '#9fbdda',
    name: ['EARTH'],
    line: 'The only world known to hold life, with its faithful Moon.',
    body: '地球表面约 71% 被海洋覆盖，是目前已知唯一存在生命的星球；夜面的点点暖光是城市灯火。月球直径约为地球的 27%，平均距离约 38.4 万公里，被潮汐锁定，始终以同一面朝向地球，并以每年约 3.8 厘米的速度远离。',
    facts: [['直径', '12,742 km'], ['月地距离', '38.4 万 km'], ['自转轴倾角', '23.4°']],
  },
  {
    key: 'mars',
    title: 'Mars',
    rail: '火星',
    cn: '火星 · 类地行星',
    zone: '距日 1.52 AU · 第 4 颗行星',
    accent: '#e2754a',
    accentMono: '#9fbdda',
    name: ['MARS'],
    line: 'A rust-red desert with the tallest volcano in the solar system.',
    body: '火星的红色来自尘土中的氧化铁。这里有太阳系最高的火山奥林帕斯山，高约 22 公里，约为珠穆朗玛峰的 2.5 倍；赤道以南横亘着长约 4000 公里的水手号峡谷。两极覆盖着由水冰和干冰组成的极冠。',
    facts: [['直径', '6,779 km'], ['一天', '24 小时 39 分'], ['平均温度', '约 −60 °C']],
  },
  {
    key: 'jupiter',
    title: 'Jupiter',
    rail: '木星',
    cn: '木星 · 气态巨行星',
    zone: '距日 5.2 AU · 第 5 颗行星',
    accent: '#d9a877',
    accentMono: '#9fbdda',
    name: ['JUPITER'],
    line: 'The king of planets, with a storm wider than the Earth.',
    body: '木星的质量是其他所有行星总和的 2.5 倍。它自转一周不到 10 小时，是自转最快的行星，高速自转把云层拉成明暗相间的条带。大红斑是一个已被持续观测了约 190 年的反气旋风暴，宽度仍超过地球直径。',
    facts: [['直径', '139,820 km'], ['自转周期', '9 小时 56 分'], ['质量', '318 个地球']],
  },
  {
    key: 'saturn',
    title: 'Saturn',
    rail: '土星',
    cn: '土星 · 气态巨行星',
    zone: '距日 9.5 AU · 第 6 颗行星',
    accent: '#e6cf98',
    accentMono: '#9fbdda',
    name: ['SATURN'],
    line: 'Rings of ice, vast as a world yet thinner than a skyscraper.',
    body: '土星的平均密度只有约 0.69 g/cm³，比水还小。它的主环由无数冰块和岩屑组成，直径约 27 万公里，大部分区域的厚度却只有约 10 米到 1 公里；环中暗色的缝隙是卡西尼环缝。北极上空盘踞着一个六边形急流，每条边都比地球直径还长。',
    facts: [['直径', '116,460 km'], ['平均密度', '0.69 g/cm³'], ['自转轴倾角', '26.7°']],
  },
  {
    key: 'uranus',
    title: 'Uranus',
    rail: '天王星',
    cn: '天王星 · 冰巨行星',
    zone: '距日 19.2 AU · 第 7 颗行星',
    accent: '#9fe0ea',
    accentMono: '#9fbdda',
    name: ['URANUS'],
    line: 'An ice giant that rolls around the Sun on its side.',
    body: '天王星的自转轴倾斜约 98°，几乎是"躺着"绕太阳公转，因此两极会轮流经历长达 42 年的极昼与极夜。大气中的甲烷吸收红光，让它呈现淡淡的青色。它还拥有 13 条暗淡而纤细的光环。',
    facts: [['直径', '50,724 km'], ['公转周期', '84 年'], ['自转轴倾角', '97.8°']],
  },
  {
    key: 'neptune',
    title: 'Neptune',
    rail: '海王星',
    cn: '海王星 · 冰巨行星',
    zone: '距日 30.1 AU · 第 8 颗行星',
    accent: '#6c9fe0',
    accentMono: '#9fbdda',
    name: ['NEPTUNE'],
    line: 'The windiest world, a planet found with mathematics.',
    body: '海王星是第一颗先由数学计算预言、再用望远镜找到的行星（1846 年）。它的风速可达约 2100 km/h，是太阳系中最快的。2024 年的研究指出，它的真实颜色是与天王星相近、略偏蓝的浅青色，而不是旅行者 2 号照片里的深蓝色。',
    facts: [['直径', '49,244 km'], ['公转周期', '165 年'], ['最高风速', '约 2100 km/h']],
  },
  {
    key: 'pluto',
    title: 'Pluto',
    rail: '冥王星',
    cn: '冥王星 · 矮行星',
    zone: '距日 39.5 AU · 曾经的第 9 颗行星',
    accent: '#e6cfa8',
    accentMono: '#9fbdda',
    name: ['PLUTO'],
    line: 'The ninth planet, with a heart of nitrogen ice.',
    body: '冥王星于 1930 年被发现，曾是第九大行星，2006 年被国际天文学联合会重新归类为矮行星。2015 年新视野号飞掠时拍到了它表面巨大的"心形"区域——汤博区，左半边的斯普特尼克平原是一片宽约 1000 公里的氮冰冰原。它稀薄的大气呈现蓝色雾霾。',
    facts: [['直径', '2,377 km'], ['公转周期', '248 年'], ['表面温度', '约 −230 °C']],
  },
  {
    key: 'galaxy',
    title: 'The Milky Way',
    rail: '银河',
    eyebrow: '银河系 · 猎户臂',
    name: ['MILKY WAY'],
    line: 'Our Sun is one star among a hundred billion or more.',
    body: '太阳位于银河系的猎户臂上，距银河系中心约 2.6 万光年，带着整个太阳系以约 230 km/s 的速度绕银心运行，转一圈约需 2.3 亿年。银河系约有 1000 亿到 4000 亿颗恒星，橙色光环标出的，就是我们的太阳。',
    accent: '#ffb347',
    accentMono: '#ffa23a',
  },
];
