// Page copy. `name` lines become the hollow neon headline (English, the
// display font); everything else is Chinese body text. `legend` explains what
// each particle colour stands for on that page.

const L = {
  mist: '#9FBDDA', pale: '#CCDBEB', ice: '#E8EEF6', steel: '#6C9AC4', deep: '#497DAE', lav: '#AEBDE6',
  glu: '#E3C27E', ca: '#8FD3D6', da: '#F0B27A', ht: '#E7A1C1', ne: '#9FE0C0', ach: '#B9A6F0', coral: '#E89A9A', amber: '#E2B77D',
};

export const PAGES = [
  {
    key: 'hero',
    rail: '序章',
    level: '',
    title: 'Neuroplasticity',
    name: ['NEUROPLASTICITY'],
    eyebrow: '从分子到心智 · 一次跨越十个层级的旅程',
    line: '神经可塑性：大脑在一生中依据经验改写自身结构与功能的能力',
    body: '每一次学习都会在大脑里留下物理痕迹：小到一个分子被磷酸化，大到一条纤维束的髓鞘增厚。向下滚动，沿参考图的组成轴自下而上，从 L1 走到 L10。移动鼠标可以拨动神经纤维；点击会发放一次动作电位；1 秒内连续点击，相当于一次“高频刺激”。',
  },
  {
    key: 'molecule',
    rail: '分子',
    level: 'L1',
    levelName: '分子 · Molecular',
    title: 'Molecule',
    name: ['MOLECULE'],
    line: 'Ca²⁺ 一闪而过，CaMKII 把这次信号写成能自我维持的分子记忆',
    body: 'NMDA 受体是“巧合探测器”：只有突触前释放谷氨酸、同时突触后膜去极化排开 Mg²⁺，Ca²⁺ 才能流入。Ca²⁺/钙调蛋白激活由 12 个亚基组成的 CaMKII 全酶，相邻亚基在 T286 位点相互磷酸化，钙信号消退后激酶仍保持活性。',
    facts: [['空间尺度', 'nm'], ['时间尺度', 'μs – 年'], ['关键分子', 'NMDAR · CaMKII · CREB']],
    evidence: 'Giese et al. (1998) · Science · CaMKIIα T286A 点突变小鼠的海马 CA1 LTP 消失，空间学习严重受损',
    legend: [[L.mist, 'CaMKII 亚基'], [L.glu, 'T286 磷酸化'], [L.ca, 'Ca²⁺'], [L.ach, '钙调蛋白'], [L.pale, 'NMDA 受体']],
  },
  {
    key: 'spine',
    rail: '亚细胞',
    level: 'L2',
    levelName: '亚细胞结构 · Subcellular',
    title: 'Dendritic spine',
    name: ['SPINE'],
    line: '树突棘几分钟内就能长大，几天里不断新生或消失：这是记忆的结构印迹',
    body: '用双光子谷氨酸解笼锁刺激单个树突棘，棘头会在数分钟内迅速增大，同时突触传递增强，这就是结构性 LTP。小鼠学会一项新的运动技能后，运动皮层在 1 小时内就长出新棘；其中少数被长期保留，保留的数量与技能记忆的保持程度相关。',
    facts: [['空间尺度', '0.1 – 1 μm'], ['时间尺度', 'ms – 天'], ['结构', '树突棘 · 突触囊泡 · 线粒体 · AIS']],
    evidence: 'Matsuzaki et al. (2004) · Nature · 单个树突棘的结构性 LTP；Xu et al. (2009) · Nature · 运动学习诱导新棘快速形成并被选择性稳定',
    legend: [[L.mist, '树突与树突棘'], [L.ca, '棘头 Ca²⁺ 内流'], [L.glu, '谷氨酸释放'], [L.ach, '线粒体']],
  },
  {
    key: 'glia',
    rail: '细胞',
    level: 'L3',
    levelName: '细胞 · Cellular',
    title: 'Neuron and glia',
    name: ['NEURON', '& GLIA'],
    line: '可塑性并非神经元独有：胶质细胞也在改写网络',
    body: '星形胶质细胞包裹突触，释放 D-丝氨酸等胶质递质，海马 LTP 的诱导依赖于此。少突胶质细胞随神经活动增加髓鞘；阻断新生少突胶质细胞的小鼠学不会复杂转轮这项新运动技能。在发育期，小胶质细胞借补体信号吞噬较不活跃的突触。',
    facts: [['空间尺度', '1 – 100 μm'], ['时间尺度', 'ms – 小时（髓鞘：天 – 周）'], ['细胞', '神经元 · 星形胶质 · 少突胶质 · 小胶质']],
    evidence: 'Henneberger et al. (2010) · Nature · LTP 依赖星形胶质释放的 D-丝氨酸；McKenzie et al. (2014) · Science · 运动技能学习需要中枢髓鞘新生',
    legend: [[L.pale, '神经元'], [L.ice, '髓鞘'], [L.lav, '星形胶质'], [L.amber, '小胶质（免疫）'], [L.coral, '毛细血管']],
  },
  {
    key: 'synapse',
    rail: '突触',
    level: 'L4',
    levelName: '突触 · Synapse',
    title: 'Synapse',
    name: ['SYNAPSE'],
    line: '一起放电的神经元，连接会变强：Hebb 法则的物质实体',
    body: '1973 年，Bliss 与 Lømo 在麻醉兔身上发现：对穿通通路施加短暂的高频刺激后，齿状回的突触传递增强，并能持续数小时，这就是长时程增强（LTP）。它的表达核心是 AMPA 受体插入突触后致密区；低频刺激则诱导长时程抑制（LTD）。',
    facts: [['空间尺度', '~1 μm（间隙 ~20 nm）'], ['时间尺度', 'ms – 小时'], ['规则', 'LTP · LTD · STDP']],
    evidence: 'Bliss & Lømo (1973) · J Physiol · 高频刺激诱导的突触增强最长持续 10 小时；Bi & Poo (1998) · J Neurosci · 放电时序依赖的可塑性',
    legend: [[L.mist, '突触前 / 后膜'], [L.glu, '谷氨酸'], [L.ice, 'AMPA 受体 · PSD'], [L.ca, 'Ca²⁺'], [L.lav, '星形胶质突起']],
  },
  {
    key: 'engram',
    rail: '微环路',
    level: 'L5',
    levelName: '微环路 / 神经元集群 · Microcircuit',
    title: 'Engram',
    name: ['ENGRAM'],
    line: '记忆被稀疏地写进一小群细胞；重新激活它们，记忆就会回来',
    body: '利根川进团队用光遗传学标记小鼠在恐惧学习时被激活的齿状回细胞；之后在一个安全的新环境中，用光重新激活这群细胞，小鼠立即出现僵直反应。哪些细胞进入印迹并不随机：CREB 水平更高、兴奋性更强的神经元更容易被招募。',
    facts: [['空间尺度', '0.1 – 1 mm'], ['时间尺度', '10 ms – s'], ['组成', '皮层柱 · E/I 平衡 · 印迹细胞集群']],
    evidence: 'Liu et al. (2012) · Nature · 光激活齿状回印迹细胞可诱发恐惧记忆提取；Han et al. (2007) · Science · CREB 高表达的神经元优先进入记忆痕迹',
    legend: [[L.ice, '印迹细胞'], [L.mist, '其他锥体细胞'], [L.ach, '抑制性中间神经元'], [L.steel, '局部连接']],
  },
  {
    key: 'hippocampus',
    rail: '脑区',
    level: 'L6',
    levelName: '脑区 / 核团 · Region',
    title: 'Hippocampus',
    name: ['HIPPOCAMPUS'],
    line: '伦敦出租车司机的后部海马更大：空间经验重塑一个脑区',
    body: 'Maguire 等用结构 MRI 发现，伦敦出租车司机的后部海马体积大于对照组，且与驾驶年限正相关。海马内部，信号沿“三突触通路”流动：内嗅皮层 → 齿状回 → CA3 → CA1。成年啮齿类的齿状回持续产生新神经元；成年人是否同样如此，至今仍有争议。',
    facts: [['空间尺度', 'mm – cm'], ['时间尺度', '100 ms – s'], ['核团', '海马 · 杏仁核 · vmPFC · dlPFC · 伏隔核']],
    evidence: 'Maguire et al. (2000) · PNAS · 后部海马体积与驾驶年限相关；【争议】Sorrells et al. (2018) Nature 与 Boldrini et al. (2018) Cell Stem Cell 结论相反',
    legend: [[L.mist, 'CA 锥体细胞层'], [L.ice, '齿状回 · 三突触脉冲'], [L.ne, '新生神经元'], [L.deep, '海马槽']],
  },
  {
    key: 'circuit',
    rail: '长程环路',
    level: 'L7',
    levelName: '长程神经环路 · Long-range circuit',
    title: 'Circuit',
    name: ['CIRCUIT'],
    line: '皮层–纹状体–丘脑–皮层环路：多巴胺告诉它哪个动作值得重复',
    body: '中脑多巴胺神经元的放电编码“奖赏预测误差”：结果比预期好时爆发，比预期差时停顿。刺激黑质能增强皮层–纹状体突触，增强幅度与动物的学习速度相关。突触前活动、突触后活动加上多巴胺，构成学习的“三因子规则”。5-HT、NE、ACh 等调制系统同样不改连接结构，只改变环路的工作状态。',
    facts: [['空间尺度', 'cm'], ['时间尺度', '100 ms – min'], ['调制', 'DA · 5-HT · NE · ACh']],
    evidence: 'Schultz, Dayan & Montague (1997) · Science · 多巴胺编码奖赏预测误差；Reynolds et al. (2001) · Nature · 黑质刺激诱导皮层–纹状体突触增强',
    legend: [[L.ice, '环路脉冲'], [L.da, '多巴胺 DA'], [L.ht, '5-羟色胺 5-HT'], [L.ne, '去甲肾上腺素 NE'], [L.ach, '乙酰胆碱 ACh']],
  },
  {
    key: 'tracts',
    rail: '白质',
    level: 'L7–8',
    levelName: '结构底座 · 白质纤维束',
    title: 'White matter',
    name: ['WHITE', 'MATTER'],
    line: '学会抛接球，白质也会改变：纤维束是长程环路与网络的“线缆”',
    body: 'Scholz 等让成年人练习杂耍 6 周，扩散张量成像显示右侧顶内沟后部下方白质的各向异性分数（FA）升高，未训练组没有这种变化。髓鞘厚度与节间长度会随神经活动调整，从而微调传导速度和环路时序。',
    facts: [['空间尺度', 'cm'], ['时间尺度', '天 – 周'], ['纤维束', '胼胝体 · 弓状束 · 扣带束 · 皮质脊髓束']],
    evidence: 'Scholz et al. (2009) · Nat Neurosci · 杂耍训练改变顶内沟下方白质结构',
    legend: [[L.pale, '左右走行'], [L.mist, '前后走行'], [L.lav, '上下走行']],
  },
  {
    key: 'networks',
    rail: '大尺度网络',
    level: 'L8',
    levelName: '大尺度脑网络 · Large-scale network',
    title: 'Networks',
    name: ['NETWORKS'],
    line: '默认模式、突显与中央执行网络：大脑在“走神”与“专注”之间切换',
    body: '静息态功能连接揭示出若干大尺度网络。默认模式网络在静息和自我参照思维时活跃；中央执行网络支撑工作记忆和目标导向任务；以前岛叶和背侧前扣带为核心的突显网络负责在两者之间切换。三网络失衡被认为与多种精神障碍有关。',
    facts: [['空间尺度', '全脑'], ['时间尺度', 's – min'], ['网络', 'DMN · SN · CEN']],
    evidence: 'Raichle et al. (2001) · PNAS · 默认模式；Sridharan, Levitin & Menon (2008) · PNAS · 右侧额岛叶在 CEN 与 DMN 之间切换',
    legend: [[L.pale, '默认模式网络 DMN'], [L.glu, '突显网络 SN'], [L.steel, '中央执行网络 CEN']],
  },
  {
    key: 'brain',
    rail: '全脑',
    level: 'L9',
    levelName: '脑 / 中枢神经系统 · Brain',
    title: 'Brain',
    name: ['BRAIN'],
    line: '约 860 亿个神经元，一生都在重新布线',
    body: '志愿者练习三球杂耍 3 个月后，双侧颞中区（hMT/V5）与左侧顶内沟后部的灰质增多；停练 3 个月后又部分回落。弦乐演奏者的左手手指在体感皮层中的代表区更大，开始学琴越早越明显。',
    facts: [['空间尺度', '全脑 · 约 1.4 kg'], ['时间尺度', 'min – 终生'], ['组成', '大脑 · 小脑 · 脑干 · 脊髓']],
    evidence: 'Draganski et al. (2004) · Nature · 杂耍训练诱导灰质可逆增多；Elbert et al. (1995) · Science · 弦乐演奏者手指皮层代表区扩大；Azevedo et al. (2009) · J Comp Neurol · 约 860 亿个神经元',
    legend: [[L.mist, '皮层（脑回亮、脑沟暗）'], [L.ice, '慢波 · 放电'], [L.steel, '小脑']],
  },
  {
    key: 'body',
    rail: '脑–身体–环境',
    level: 'L10',
    levelName: '脑–身体–环境系统 · Brain–Body–Environment',
    title: 'Body and world',
    name: ['BODY', '& WORLD'],
    line: '应激、运动、睡眠、肠道与社会环境，都在调节可塑性',
    body: '慢性应激经 HPA 轴升高糖皮质激素，可使大鼠海马 CA3 神经元的树突萎缩，杏仁核神经元的树突反而增生。另一方面，一项随机对照试验中，老年人坚持有氧运动一年，前部海马体积增大约 2%，抵消了 1–2 年的增龄性萎缩。',
    facts: [['空间尺度', '全身 / 社会'], ['时间尺度', 'min – 终生'], ['通路', '内感受 · HPA 轴 · 肠–脑轴 · 自主神经']],
    evidence: 'Vyas et al. (2002) · J Neurosci · 慢性应激下海马与杏仁核树突呈相反重塑；Erickson et al. (2011) · PNAS · 有氧运动使老年人海马体积增大',
    legend: [[L.mist, '中枢与周围神经'], [L.coral, '心脏'], [L.amber, 'HPA 轴 · 皮质醇'], [L.steel, '环境与他人']],
  },
  {
    key: 'outro',
    rail: '终章',
    level: '',
    title: 'Keep rewiring',
    name: ['KEEP', 'REWIRING'],
    eyebrow: '组成 · 连接 · 支撑 · 调制 · 实现',
    line: '可塑性是双向的：用进，也会废退',
    body: '参考图中的五种层级关系，在每一次学习中同时发生：分子开关写下变化，树突棘与髓鞘把它固定成结构，胶质与血管提供支撑，调制系统决定何时值得写入；最终，这些变化在认知、情绪与行为中得以实现。',
  },
];
