"""Downsample the GLOBE 1 km land mask to a 1-degree bitmap for the Earth model.

Source: the `global-land-mask` package on PyPI (NOAA GLOBE dataset).

    pip download --no-deps global-land-mask   # unzip the wheel
    python3 solar/tools/make_landmask.py <path>/globe_combined_mask_compressed.npz

Writes solar/src/shapes/landmask.js: 360 x 180 cells, row 0 at 90°N, column 0
at 180°W, one bit per cell (1 = land), base64 encoded.
"""
import base64
import sys
from pathlib import Path

import numpy as np

d = np.load(sys.argv[1])
water = d["mask"]  # True = ocean in this dataset
H, W = 180, 360
k = water.shape[0] // H
land = (~water).reshape(H, k, W, k).mean(axis=(1, 3)) > 0.42
bits = np.packbits(land.astype(np.uint8).ravel())
b64 = base64.b64encode(bits.tobytes()).decode()
out = Path(__file__).resolve().parent.parent / "src/shapes/landmask.js"
out.write_text(
    "// 1-degree land mask of Earth (NOAA GLOBE via the global-land-mask package).\n"
    "// Generated by solar/tools/make_landmask.py — 360 x 180 bits, row 0 = 90°N, col 0 = 180°W.\n"
    f"export const LAND_W = {W};\nexport const LAND_H = {H};\n"
    f"export const LAND_B64 = '{b64}';\n"
)
print(out, f"{land.mean():.3f} land fraction", len(b64), "chars")
