// Page copy. `name` lines become the hollow neon headline; `line` is the
// hollow neon description; `body` and `facts` are set in plain type for reading.

export const PAGES = [
  {
    key: 'hero',
    title: 'Luminous Deep',
    rail: 'Surface',
    eyebrow: 'A fluorescent field guide to the ocean',
    name: ['LUMINOUS', 'DEEP'],
    line: 'Seven creatures, drawn in living light.',
    body: 'Scroll to descend from the sunlit reef to the midnight zone. Move your cursor through the water, and click to send out a pulse of light.',
  },
  {
    key: 'turtle',
    title: 'Sea turtle',
    rail: 'Sea turtle',
    zone: 'Sunlit zone · coral reef',
    accent: '#3dff8e',
    name: ['SEA', 'TURTLE'],
    latin: 'Eretmochelys imbricata · hawksbill',
    line: 'The first reptile ever seen to glow.',
    body: 'In 2015 marine biologist David Gruber was filming biofluorescent sharks off the Solomon Islands when a hawksbill swam into his blue light and lit up neon red and green. Nobody yet knows why its shell glows.',
    facts: [['Shell', 'up to 1 m'], ['Habitat', 'Tropical reefs'], ['Status', 'Critically endangered']],
  },
  {
    key: 'manta',
    title: 'Manta ray',
    rail: 'Manta ray',
    zone: 'Sunlit zone · Great Barrier Reef',
    accent: '#ff4fb4',
    name: ['MANTA', 'RAY'],
    latin: 'Mobula alfredi · reef manta',
    line: 'Somewhere off the reef glides a manta that is pink.',
    body: 'Off Lady Elliot Island swims Inspector Clouseau, a reef manta with a bubble-gum pink belly, first photographed in 2015. A skin biopsy ruled out infection and diet, which leaves a rare colour mutation called erythrism as the likely cause.',
    facts: [['Wingspan', 'up to 5 m'], ['First seen', '2015'], ['Diet', 'Zooplankton']],
  },
  {
    key: 'whale',
    title: 'Blue whale',
    rail: 'Blue whale',
    zone: 'Open ocean',
    accent: '#8a8dff',
    name: ['BLUE', 'WHALE'],
    latin: 'Balaenoptera musculus',
    line: 'The largest animal that has ever lived.',
    body: 'A blue whale can grow to 30 metres and weigh more than 150 tonnes. Its calls sit near the bottom edge of human hearing and can carry for hundreds of kilometres through the ocean.',
    facts: [['Length', 'up to 30 m'], ['Heart', '~180 kg'], ['Call', '10–40 Hz']],
  },
  {
    key: 'lanternfish',
    title: 'Lanternfish',
    rail: 'Lanternfish',
    zone: 'Twilight zone · 200–1,000 m',
    accent: '#ffc94a',
    name: ['LANTERN', 'FISH'],
    latin: 'Family Myctophidae',
    line: 'Tiny lanterns on the largest daily migration on Earth.',
    body: 'Every night lanternfish rise hundreds of metres toward the surface to feed, then sink back before dawn. Rows of photophores along their bellies match the faint light from above, hiding their silhouettes from hunters below.',
    facts: [['Species', '~250'], ['Length', '2–30 cm'], ['By day', '300–1,500 m']],
  },
  {
    key: 'jellyfish',
    title: 'Jellyfish',
    rail: 'Jellyfish',
    zone: 'Midnight zone · 1,000–4,000 m',
    accent: '#2fd6ff',
    name: ['JELLY', 'FISH'],
    latin: 'Class Scyphozoa · e.g. Atolla wyvillei',
    line: 'When attacked, it calls for help in blue light.',
    body: 'The alarm jellyfish Atolla spins rings of blue light around its bell when grabbed, a display that may lure bigger predators to eat whatever is attacking it. In 2012 an electronic lure copying this display helped scientists film a giant squid in the deep sea for the first time.',
    facts: [['Bell', '2–15 cm'], ['Light', 'Blue flashes'], ['Lineage', '500+ million yrs']],
  },
  {
    key: 'anglerfish',
    title: 'Anglerfish',
    rail: 'Anglerfish',
    zone: 'Midnight zone',
    accent: '#e9ff4a',
    name: ['ANGLER', 'FISH'],
    latin: 'Melanocetus johnsonii · black seadevil',
    line: 'A lantern on a fishing rod, lit by borrowed bacteria.',
    body: 'The female’s lure, the esca, is packed with symbiotic bacteria that make the light for her. In some anglerfish species the tiny male bites onto a female and fuses with her for life, sharing her bloodstream.',
    facts: [['Female', 'up to 18 cm'], ['Male', '~3 cm'], ['Light', 'Bacterial']],
  },
  {
    key: 'eel',
    title: 'Electric eel',
    rail: 'Electric eel',
    zone: 'Freshwater · Amazon basin',
    accent: '#c6ff3a',
    name: ['ELECTRIC', 'EEL'],
    latin: 'Electrophorus voltai',
    line: 'A living battery that discharges 860 volts.',
    body: 'Despite the name it is a knifefish, closer to catfish than to true eels, and it breathes air in South American rivers. Thousands of electrocytes stacked like cells in a battery give Volta’s electric eel the strongest discharge known in any animal. It does not glow; the light here draws its current.',
    facts: [['Discharge', 'up to 860 V'], ['Length', 'up to 2.5 m'], ['Breathes', 'Air']],
  },
  {
    key: 'outro',
    title: 'Keep the deep glowing',
    rail: 'Ascend',
    eyebrow: 'Back toward the light',
    name: ['KEEP THE DEEP', 'GLOWING'],
    line: 'Three in four open-ocean animals make their own light.',
    body: 'Video surveys of the water column off California found that 76% of observed animals were bioluminescent (Martini & Haddock, Scientific Reports, 2017). Most of that light has never been seen by a person.',
  },
];
